### ISSUE TITLE
Material Design + light/dark theme support

### ISSUE THREAD

**Issue by chaosfreak93** [justdave/MCStatus#23]

**Comment by justdave** [comment]
Not sure what this is about.... Did you have something in mind?

**Comment by chaosfreak93** [comment]
A more modern Design. Light and Dark theme

**Comment by chaosfreak93** [comment]
![Screenshot_20200831-075342.png](https://user-images.githubusercontent.com/36674649/91687049-24338c80-eb5f-11ea-984f-c5888629e7e0.png) Display a Offline Message and not this error

**Comment by justdave** [comment]
Can you move your last comment (about the error message) to a new issue report?

Proper Material Design support with system theme support sounds like a good idea to me. Definitely past due for it.

**Comment by chaosfreak93** [comment]
Is it okay when i fork your Project and i rewrite/optimize it?
