### ISSUE TITLE
Offline Message

### ISSUE THREAD

**Issue by chaosfreak93** [justdave/MCStatus#24]
![error](https://user-images.githubusercontent.com/36674649/91693535-6f539c80-eb6b-11ea-8cf5-90b84437b325.png)
Display a Offline Message and not this error

**Comment by chaosfreak93** [comment]
Offline or Query disabeld

**Comment by justdave** [comment]
I think the actual error would be useful for debugging (given that the stated purpose of this app is for admins to monitor their servers) but it can probably be hidden and give some way to show it if you really want it. Or at least come up with more human-friendly messages :-)
