### ISSUE TITLE
Localize Play Store listing for German

### ISSUE THREAD

**Issue by justdave** [justdave/MCStatus#32]
@chaosfreak93 if you have a few minutes to look at this it would be great.

In the root level of the project, I've added a <code>playstore</code> directory that contains the store listing data for each locale (en is the only one with anything in it).
If you could translate that for me so I can update the listing in addition to just the app, it would be great.
Thanks!

**Comment by chaosfreak93** [comment]
I will take a look later. Now I have to do homework. ;D

**Comment by chaosfreak93** [comment]
I will also update the German Localization of the App.

**Comment by chaosfreak93** [comment]
Close?

**Comment by justdave** [comment]
Yes.

Fixed by cd1c573c08ff8823bbbf407b93d33bf23749e7f3

**Comment by chaosfreak93** [comment]
Then Close this issue
