### ISSUE TITLE
Release version 1.0.8

### ISSUE THREAD

**Issue by chaosfreak93** [justdave/MCStatus#43]
It would be nice if you could release a new update since the version on google play is 2 versions behind

**Comment by justdave** [comment]
Ah yes.  Usually I bump the version number every time I push to Google Play, forgot we'd been bumping it with your PRs.

**Comment by justdave** [comment]
The version bump to 1.0.7 and the version bump to 1.0.8 were both in the same PR.  How'd we do that one?  I should have killed the 1.0.8 bump when I merged it. :-)  Would probably be confusing at this point.

**Comment by justdave** [comment]
This has been submitted, just waiting for them to approve it now.

**Comment by chaosfreak93** [comment]
> The version bump to 1.0.7 and the version bump to 1.0.8 were both in the same PR.  How'd we do that one?  I should have killed the 1.0.8 bump when I merged it. :-)  Would probably be confusing at this point.

We already had 1.0.7 before my last PR, we only forgot to bump the version

**Comment by justdave** [comment]
Still hasn't been approved.  On the plus side, they haven't denied it either. :)  They're just being slow.

**Comment by justdave** [comment]
Update has been approved.
