### ISSUE TITLE
cannot delete or edit server

### ISSUE THREAD

**Issue by pakleonghui** [justdave/MCStatus#8]
cannot delete or edit server

**Comment by justdave** [comment]
What happens when you try? Are you getting an error?

**Comment by pakleonghui** [comment]
No

**Comment by pakleonghui** [comment]
When I test the app on emulator , I can delete or edit server ,but when I test on my mobile phone(lenovo A7000) the bug occour

**Comment by justdave** [comment]
You still haven't answered the question. What happens when you try to edit or delete?  Does it not allow you to select a server? Can you select it but the toolbar doesn't show up? Do you get a toolbar but tapping the icons on it doesn't do anything? etc.

**Comment by justdave** [comment]
@pakleonghui any answer? Otherwise I'll close this as "can't reproduce" soon
